export enum StatTypeEnum {
  // ⚽ Attacking
  ASSIST = "ASSIST",
  PRE_ASSIST = "PRE_ASSIST",
  BIG_CHANCE_CREATED = "BIG_CHANCE_CREATED",
  BIG_CHANCE_MISSED = "BIG_CHANCE_MISSED",

  SHOT_ON_TARGET = "SHOT_ON_TARGET",
  SHOT_OFF_TARGET = "SHOT_OFF_TARGET",
  SHOT_BLOCKED = "SHOT_BLOCKED",
  SHOT_HIT_POST = "SHOT_HIT_POST",

  GOAL_FROM_INSIDE_BOX = "GOAL_FROM_INSIDE_BOX",
  GOAL_FROM_OUTSIDE_BOX = "GOAL_FROM_OUTSIDE_BOX",
  OWN_GOAL = "OWN_GOAL",

  DRIBBLE_SUCCESS = "DRIBBLE_SUCCESS",
  DRIBBLE_FAILED = "DRIBBLE_FAILED",

  // 🎯 Passing
  PASS_COMPLETED = "PASS_COMPLETED",
  PASS_FAILED = "PASS_FAILED",

  LONG_PASS_COMPLETED = "LONG_PASS_COMPLETED",
  LONG_PASS_FAILED = "LONG_PASS_FAILED",

  CROSS_COMPLETED = "CROSS_COMPLETED",
  CROSS_FAILED = "CROSS_FAILED",

  KEY_PASS = "KEY_PASS",
  PROGRESSIVE_PASS = "PROGRESSIVE_PASS",

  // 🛡 Defensive
  TACKLE = "TACKLE",
  INTERCEPTION = "INTERCEPTION",
  BLOCK = "BLOCK",
  CLEARANCE = "CLEARANCE",

  DUEL_WON = "DUEL_WON",
  DUEL_LOST = "DUEL_LOST",

  AERIAL_DUEL_WON = "AERIAL_DUEL_WON",
  AERIAL_DUEL_LOST = "AERIAL_DUEL_LOST",

  POSSESSION_LOST = "POSSESSION_LOST",
  BALL_RECOVERY = "BALL_RECOVERY",

  // 🧤 Goalkeeper
  SAVE = "SAVE",
  SAVE_INSIDE_BOX = "SAVE_INSIDE_BOX",
  SAVE_OUTSIDE_BOX = "SAVE_OUTSIDE_BOX",
  PENALTY_SAVE = "PENALTY_SAVE",
  GOAL_CONCEDED = "GOAL_CONCEDED",

  // ⚖ Discipline
  FOUL_COMMITTED = "FOUL_COMMITTED",
  FOUL_SUFFERED = "FOUL_SUFFERED",

  YELLOW_CARD = "YELLOW_CARD",
  SECOND_YELLOW_CARD = "SECOND_YELLOW_CARD",
  RED_CARD = "RED_CARD",

  // 🏃 Movement / Advanced
  ERROR_LEADING_TO_SHOT = "ERROR_LEADING_TO_SHOT",
  ERROR_LEADING_TO_GOAL = "ERROR_LEADING_TO_GOAL",

  PENALTY_WON = "PENALTY_WON",
  PENALTY_MISSED = "PENALTY_MISSED",
  PENALTY_SCORED = "PENALTY_SCORED",
  PENALTY_CONCEDED = "PENALTY_CONCEDED",
  FREE_KICK_SCORED = "FREE_KICK_SCORED",
}

export enum ImpactEnum {
  POSITIVE = 1,
  NEGATIVE = -1,
}
